### ISSUE TITLE
Does packages' including not work?

### ISSUE THREAD

**Issue by ghost** [marcellino-ornelas/create-react-component#9]
I call ccr like this:
`ccr create --packages pac1:pac2:pac3 Test`
but i don't see packages in my component.
What am I doing wrong?

**Comment by marcellino-ornelas** [comment]
Hey @svetley1 thank you for reporting this issue. Sorry, its took me so long to reply. Let me figure out what's going on and I will get back to you as soon as I can 🙇

**Comment by marcellino-ornelas** [comment]
Hey @svetley1, I was able to look into this issue for you but unfortunately, I wasn't able to reproduce the same behavior. 

![Screen Shot 2020-06-29 at 7 45 35 PM](https://user-images.githubusercontent.com/35247622/86077681-4155bd00-ba41-11ea-9c3d-b5fb0d0360de.png)

It possible it has something to do with your layout or `.ccr/settings.json`. Would you mind providing the layout of your `.ccr` folder and the JSON object you have in your `.ccr/settings.json`?

>if the `templates` property isn't set to `true` it will use the default templates instead of the ones your developing on.
>https://github.com/marcellino-ornelas/create-components-react#examples-2

**Comment by marcellino-ornelas** [comment]
User deleted account
